### ISSUE TITLE
SB Rapido Toolhead Mount (Front) Beta 4 

### ISSUE THREAD

**Issue by flyespresso** [VoronDesign/Voron-Afterburner#101]
On the bleed air ports, I they're not fully extruded on the Rapido toolhead. Printed and can verify nothing passes through, looked at SS slice (with PIF settings) and confirmed, then took look at STL and yeah, they never intersect. Confirmed as an issue with wile.e & timbot99 on Discord. Adding here as requested :)

Video on Discord: https://cdn.discordapp.com/attachments/923325119454126090/949021443730079804/Screen_Recording_2022-03-03_at_11.01.08_AM.mov

Part Link: https://github.com/VoronDesign/Voron-Afterburner/blob/sb-beta/STLs/Stealthburner/Toolheads/phaetus_rapido/stealthburner_toolhead_(rapido)-front-beta4.stl

<img width="788" alt="Screen Shot 2022-03-03 at 11 06 40 AM" src="https://user-images.githubusercontent.com/1707612/156636811-477abdc3-e548-4391-8143-4c0245fc7c63.png">
<img width="788" alt="Screen Shot 2022-03-03 at 11 07 01 AM" src="https://user-images.githubusercontent.com/1707612/156636818-f4f07ea0-0cc3-4df2-a752-f56d3a97363f.png">

**Comment by wile-e1** [comment]
This issue has been corrected in PR #103 

Thanks for bringing it out our attention.
