### ISSUE TITLE
Missing perimeters in stealthburner_toolhead_(v6_r6)-rear-cw1/2-beta3

### ISSUE THREAD

**Issue by Promix953** [VoronDesign/Voron-Afterburner#102]
![v6-1](https://user-images.githubusercontent.com/22642692/156824111-4b5d8580-42b1-48de-a05e-f96857886f23.png)
![v6-2](https://user-images.githubusercontent.com/22642692/156824135-3b158be8-feae-4456-9673-96ee7929590d.png)
![V6-3](https://user-images.githubusercontent.com/22642692/156824138-561bc84d-2db6-455f-ba0c-372117b9f80f.png)

**Comment by wile-e1** [comment]
This issue has been corrected in PR #103 

Thanks for the bug report!

**Comment by Promix953** [comment]
> This issue has been corrected in PR #103
> 
> Thanks for the bug report!

![image](https://user-images.githubusercontent.com/22642692/156873408-2bf29efd-e84a-471c-bb8a-f391f310b26e.png)

The left hole still has problem
