### ISSUE TITLE
stealthburner main body causes crashing in simplify 3d 

### ISSUE THREAD

**Issue by Balinerd** [VoronDesign/Voron-Afterburner#110]
when trying to slice the stealthburner main body in simplify 3d at 0.2 mm layer height with 4 walls is causes a crash.

**Comment by Steven23456** [comment]
I've sliced the beta 6 in SuperSlicer 2.3 (a fork of PrusaSlicer) & Cura 4.13 at .2mm with no issue.

**Comment by CorvusOculum** [comment]
SuperSlicer is a fork of PrusaSlicer.  Simplify 3D is an older closed source slicer.

**Comment by CrazyCreator13** [comment]
> when trying to slice the stealthburner main body in simplify 3d at 0.2 mm layer height with 4 walls is causes a crash.

can you link the file "stealth burner main body" ... I can't find for try with my S3D version.

**Comment by Balinerd** [comment]
> > when trying to slice the stealthburner main body in simplify 3d at 0.2 mm layer height with 4 walls is causes a crash.
> 
> can you link the file "stealth burner main body" ... I can't find for try with my S3D version.

Under stls

https://github.com/VoronDesign/Voron-Afterburner/releases

**Comment by CrazyCreator13** [comment]
![Bildschirmfoto 2022-04-08 um 21 02 06](https://user-images.githubusercontent.com/3821732/162507879-0035732d-62ee-489b-8aa5-6bc8b3160ea1.png)
![Bildschirmfoto 2022-04-08 um 21 04 03](https://user-images.githubusercontent.com/3821732/162507982-d3cf6ac6-9f0d-4d95-ab79-5c7d44294b66.png)

No problem

**Comment by CrazyCreator13** [comment]
![Bildschirmfoto 2022-04-08 um 21 08 39](https://user-images.githubusercontent.com/3821732/162508550-96c62adf-5e8f-48fa-885c-81fae93b6d89.png)

**Comment by raymondh2** [comment]
> > > when trying to slice the stealthburner main body in simplify 3d at 0.2 mm layer height with 4 walls is causes a crash.
> > 
> > 
> > can you link the file "stealth burner main body" ... I can't find for try with my S3D version.
> 
> Under stls
> 
> https://github.com/VoronDesign/Voron-Afterburner/releases

Those are not the latest STLs. Please read the notes on that page

**Comment by CrazyCreator13** [comment]
It's not about whether it's up-to-date. it's about the fact that he couldn't slice them with s3d

**Comment by raymondh2** [comment]
That does matter. As the old slicing the old STLs doesn't tell us if the current ones have issues.

**Comment by CrazyCreator13** [comment]
But I don't find the newest version ... 
or rather: I just wanted to show the questioner that it is not because of the stl. not more

**Comment by raymondh2** [comment]
I have talked with some Simplify3D users on the Voron team and none of them have ran into issues. I suggest you contact Simplify3D support for assistance. https://www.simplify3d.com/contact-us/
