### ISSUE TITLE
Toolhead-Front Heat Set Hole Diameters are 4.6mm vs 4.7mm

### ISSUE THREAD

**Issue by SkiBikePrint** [VoronDesign/Voron-Afterburner#111]
A small nit...  :)

Identified on "stealthburnertoolhead(dragon)-front-beta4.stl".

![image](https://user-images.githubusercontent.com/99146508/162492183-be51c637-541c-45da-a5f3-15e396ce8b69.png)

**Comment by wile-e1** [comment]
Fixed on PR #112
