### ISSUE TITLE
Where is Trimming jig stl

### ISSUE THREAD

**Issue by XEL-Maker** [VoronDesign/Voron-Afterburner#114]
I know stealthburner is beta version.
I was trying to build by referring to the old manual, 
but I couldn't find it wherever trimming jig looked. 
I threw away one blower while trying to work without a jig.

**Comment by mathisschmieder** [comment]
https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/Badnoob/AB-BN/STL_files/5015-deearing-tool.stl
https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/Badnoob/AB-BN/STL_files/5015-deearing-tool-b.stl

**Comment by XEL-Maker** [comment]
Thanks alot
