### ISSUE TITLE
Non-connectness of inner/outer walls leads to more seams

### ISSUE THREAD

**Issue by grmocg** [VoronDesign/Voron-Afterburner#119]
With the current StealthAB model (currently Beta7), the inner and outer walls of the SB are likely to be connected via infill, and this leads to seam lines on the outer walls of the SB. More icky than needed.

If we added a small void between the inner and outer walls of the SB, we'd be likely to trick slicers into connecting the inner/outer walls by running a wall along the sides of the void, which would lead to "moar prettier prints".

Wall == Perimeter.

**Comment by grmocg** [comment]
Am referring to the "Main Body" piece, which is the one that arguably has the largest cosmetic impact.

**Comment by raymondh2** [comment]
How many walls are you using? You shouldn't be seeing the infill connections.

**Comment by grmocg** [comment]
I've done 4 prints at 3 wall.

I'm not seeing the infill connections, I'm seeing the seam starts for the layer(s), and observing that if the perimeters were connected from the outer-to-the-inner, there'd be half as many seam starts.

**Comment by grmocg** [comment]
![Screenshot 2022-04-25 095007](https://user-images.githubusercontent.com/1006962/165136132-9c0f2dec-c6c8-43eb-894e-6c856e8cb4de.png)

Looking at seam lines like the one highlighted in this screenshot

**Comment by raymondh2** [comment]
You appear to only be using a single wall. Voron spec is 4 walls.

**Comment by grmocg** [comment]
Ah yea, I see how that image could confuse-- I have the first layer only use one perimeter. The rest uses the thicker walls.
![Screenshot 2022-04-25 101755](https://user-images.githubusercontent.com/1006962/165140503-c2e071c7-5099-4ebe-8e01-170a5c28a80b.png)

have been attempting to convert the STL to a solid body so I can edit it, but SW hasn't been very cooperative thusfar.

**Comment by grmocg** [comment]
Here is a photoshop edit that sorta shows what I'm poorly communicating:

Here I'm faking putting a void between the perimeters of the outer wall and the inner wall, and approximating what a slicer might do with it.

![Screenshot 2022-04-25 102808](https://user-images.githubusercontent.com/1006962/165141882-02ab709d-eb80-459a-9228-fa4895f22253.png)

**Comment by grmocg** [comment]
I'll just close this for now. When the step is out, I'll submit something for the next rev if it works.

**Comment by wile-e1** [comment]
There is an inner profile and an outer profile, how are you suggesting that you make a closed profile without having a start and a stop?

**Comment by grmocg** [comment]
It'd still have a start and stop. The hope would be that it'd have one
fewer start+stop, if the inner and outer are connected.
I'll play around with things after the step is out to see if it works on
this.

**Comment by wile-e1** [comment]
If you're getting artifacts on your start/stops, it means you need to do some more tuning.  I don't think relying on trickery is a substitute for proper tuning.
