### ISSUE TITLE
How to use adxl_washer

### ISSUE THREAD

**Issue by XEL-Maker** [VoronDesign/Voron-Afterburner#125]
I printed out the parts needed for adxl 345 mounting. 
There was also a washer_x2, so I printed it, but I couldn't imagine how it would be assembled.
Someone asked for an image on a closed issue related to this, but there has been no comment since.

**Comment by XEL-Maker** [comment]
I tried a few more times after writing the issue.
And I assembled it as shown in the picture.
Do you fix the adxl with m2 self tapping?
![howtoassem](https://user-images.githubusercontent.com/52307315/166110863-649d870a-c31c-4b67-a029-f2137a778995.jpg)

**Comment by kaibsora** [comment]
you fix it with the supplied washers that are in the same folder, with the m2 self tapping screws. the screws go through the washer, and then self thread into the mount. you cant just use the screws, as the holes are too big, the washers fix that issue. 

It is also not meant to be permanently mounted.

**Comment by BeardedTinker** [comment]
Also, the washers have cutout on one of the surfaces - that part goes over those capacitors near the hole to protect them from both contact and damage if thightening too much.
![image](https://user-images.githubusercontent.com/47822612/166441088-d571a415-d1af-41c2-8e95-12d2266d6f87.png)

**Comment by XEL-Maker** [comment]
Thank you for the information.
I'll have to install it as needed.
