### ISSUE TITLE
cable door problem

### ISSUE THREAD

**Issue by XEL-Maker** [VoronDesign/Voron-Afterburner#126]
When applying toolhead pcb, interference occurred in cable door, so processing was performed. 
Could you add the version where the area was removed?
![toolhead](https://user-images.githubusercontent.com/52307315/166111367-e6459a9f-b2f0-40ee-93e8-ca99d13f03f0.png)

I used this pcb.
https://github.com/hartk1213/MISC/tree/main/PCBs/Stealthburner_Toolhead_PCB

res:
![plz](https://user-images.githubusercontent.com/52307315/166111531-385be456-41cd-4f56-b17d-6377adc10ea2.jpg)

For the smooth mounting of the substrate and CW2, 
two 3.3mm thick spacer was used.
Interference still occurs even when the spacer is not used.

**Comment by raymondh2** [comment]
This is not the repo to report this issue. As the PCB is not an official part of CW2
