### ISSUE TITLE
Clockwork2 MR85ZZ bearing housings in the motor plate and main housings are different diameters, 8.2mm and 8.1mm

### ISSUE THREAD

**Issue by andrew-benjamin** [VoronDesign/Voron-Afterburner#128]
When printing both parts with identical settings I found the bearing fitted easily in the main body but would not fit in the motor plate housing. Measuring the .stl gives 8.1mm for motor_plate-beta10.stl and 8.2mm in main_body-beta11.stl. 
8.2mm was preferable for a gentler push fit without warming the ABS.

**Comment by iwm911** [comment]
I didn't checked the stl size but I can say that the bearing just doesn't fit in the motor plate.
I can push it in but then it clicks when the gear is turning

**Comment by raymondh2** [comment]
Closing as beta has ended
