### ISSUE TITLE
Minor printability issue in printhead_front_dragon.stl

### ISSUE THREAD

**Issue by trchen1033** [VoronDesign/Voron-Afterburner#131]
Due to the addition of cable tie ears near the right air duct, the induced perimeter walls pushed bridge infill over the cliff.

![defect3](https://user-images.githubusercontent.com/22458659/172917314-a5d01a6b-16b0-4a60-953d-aa024d3c74a3.jpg)

The infill makes mid-air U turns with nothing to cling on to.

**Comment by raymondh2** [comment]
Closing as beta has ended
