### ISSUE TITLE
Clockwork2 lack of filament grip

### ISSUE THREAD

**Issue by bartoszwas** [VoronDesign/Voron-Afterburner#132]
Hey,

I've printed the last beta Clockwork 2. Issue is that I got lack of filament grip. When I put filament in and close the latch I can pull it out without moving the gears. Teeth leave almost no sign on filament so its skipping and I got under-extrusion.

**Comment by nemesina** [comment]
Same problem here. With latest stl's.

**Comment by Clarkbf** [comment]
I had the same problem. Went back to CW1 because I did not see anyone else raise the issue. Usually with something like this it is user error so I didn't bring it up, even though I tried many different ways to get it to work.

**Comment by hmouridsen** [comment]
From my experience the latch shuttle needs some exercise - making is moving freely, and gain the tension on the gears

**Comment by raymondh2** [comment]
Closing as beta has ended
