### ISSUE TITLE
[suggestion] Stealthburner add missing STL for X Carriage

### ISSUE THREAD

**Issue by pdion891** [VoronDesign/Voron-Afterburner#133]
Hi, 
Would it make sense to add following stl files to the X Carriage since these are required to complete the installation of straps and bottom 9mm rail ?

* https://github.com/VoronDesign/Voron-2/blob/V2.4r1/STLs/VORON2.4/Gantry/X_Axis/X_Carriage/%5Ba%5D_belt_clamp_x2.stl
* https://github.com/VoronDesign/Voron-2/blob/V2.4r1/STLs/VORON2.4/Gantry/X_Axis/X_Carriage/x_carriage_pivot_block.stl

Regards,

**Comment by raymondh2** [comment]
Fixed in release
