### ISSUE TITLE
Add hotend compatibility notes

### ISSUE THREAD

**Issue by andrhamm** [VoronDesign/Voron-Afterburner#16]
I'm new to the Voron community and was trying to determine which printhead parts to print for my Phaetus X Voron Dragon HF hotend. On Discord I was told to use the `TriangleLab_Dragon` models. I'd never heard of TriangleLab but this is apparently the same hotend made by the same manufacturer. A readme in the printheads directory might be a good place to put these kinds of notes where the models support multiple hotends or variants thereof.

**Comment by LoganFraser** [comment]
The same factory makes the triangle lab and phaetus/BTT Dragon hotends. It's all the same except for the rectangle vs D shaped heat block

**Comment by wile-e1** [comment]
This should be taken care of in the last pull-request that I submitted.
