### ISSUE TITLE
Holes in [a]_stealthburner_main_body_beta0.stl

### ISSUE THREAD

**Issue by elcrni** [VoronDesign/Voron-Afterburner#22]
Hotend cooling fan bay has 3 corners rounded and one left without fillet, this results in slicer having issues and the print has a hole in the wall. as seen on attached images
![Screenshot 2021-12-27 011000](https://user-images.githubusercontent.com/74976689/147423271-b9e3a63a-edb1-439e-ac20-da9a96d950c9.png)
![Screenshot 2021-12-27 011022](https://user-images.githubusercontent.com/74976689/147423273-5d2920b5-1294-4eea-8694-e2960eaf0649.png)
.

**Comment by tnap1979** [comment]
![16405776472414190809211001055628](https://user-images.githubusercontent.com/1660801/147433052-e53d6fac-a61b-4384-80c9-3d5a4932c414.jpg)
Seems to be more of a cosmetic concern and less of a leak or performance issue.. but it's there none the less

**Comment by FHeilmann** [comment]
Which slicer are you using? What's your "detect thin walls" setting?
Here's my slicing result with PrusaSlicer 2.4.0 and "Detect thin walls" enabled:

![image](https://user-images.githubusercontent.com/4352664/147497766-770c2ced-6072-4bef-a458-b7a2b79c46f4.png)

**Comment by elcrni** [comment]
Also using Prusa 2.4, mz settings as attached
![Screenshot 2021-12-27 192548](https://user-images.githubusercontent.com/74976689/147497908-49f56e05-fa76-4ba5-b396-a739d4582f27.png)

**Comment by FHeilmann** [comment]
what are your extrusion widths?

edit:
try forcing your extrusion widths to 0.4, this is what happens when I set them to 0 (auto)

![image](https://user-images.githubusercontent.com/4352664/147499497-4ff94f9b-eee5-49b9-a637-099adefb5f6a.png)

**Comment by elcrni** [comment]
All my extrusions are forced to 0.4mm

**Comment by wile-e1** [comment]
This issue has been corrected with the update of [a]_stealthburner_main_body_beta1.stl

The missing fillet was added and material was also added to the front facets to help increase the wall thickness on this layer.

**Comment by raymondh2** [comment]
Issue fixed in #21 Will leave open for three days before closing to confirm fix.

**Comment by elcrni** [comment]
Is there a file [a]_stealthburner_main_body_beta1.stl available to download somewhere to test? many thanks

**Comment by raymondh2** [comment]
https://github.com/VoronDesign/Voron-Afterburner/blob/sb-beta/STLs/Stealthburner/a_stealthburner_main_body_beta1.stl
