### ISSUE TITLE
Phaetus BMS part cooling ducts are too high

### ISSUE THREAD

**Issue by DorjeDorf** [VoronDesign/Voron-Afterburner#26]
I just finished mounting a Phaetus BMS onto the SB. 
I noticed the ducts are high enough that they blow onto the heatblock - especially if a sock is present. This is very visible also during PID tuning. 

Photos attached. 
![IMG_1109](https://user-images.githubusercontent.com/45540765/147498194-d13e7aff-63e5-462c-b0ca-bffc74bf8d3d.jpeg)
![IMG_1108](https://user-images.githubusercontent.com/45540765/147498204-ed1796ae-1c99-468d-b1a5-153ed4d7e05b.jpeg)

**Comment by wile-e1** [comment]
Can you please measure from the top of the toolhead to the tip of the nozzle?

I check the CAD and everything matches what it should be.  I did, however, find an issue with the CAD provided by Phaetus that showed the radius of the heatsink being 3mm but in reality it is more like 1.5-2mm so I have a feeling that your hotend may not be seated fully.

**Comment by plumpcheek** [comment]
Mine Phaetus BMS with beta0 toolhead and I measured from the tip of nozzle to the top toolhead (w/o ptfe collar) is 48.93 mm.
![IMG_0448](https://user-images.githubusercontent.com/83712689/147690275-ff7eb54b-2a14-45a1-997d-468bb7d733bc.jpg)
.

**Comment by DorjeDorf** [comment]
In my case it's 51mm.

When you say hotend not being seated fully - do you mean the heatbreak in the heatsink or rather the whole thing inside of the printed part? If it's the latter - below is a picture to show the fitment. 

The one thing that has me curious is also visible on the photo from @plumpcheek - should a part of the heatsink be sticking out like that? My BMS is black and it's a touch more tricky to capture on a photo, but I see the same thing. 


![IMG_1112](https://user-images.githubusercontent.com/45540765/147692335-0a5bc51d-a482-4079-9dd2-bc8777af1cc8.jpeg)

**Comment by plumpcheek** [comment]
Well, look like Phaetus strike again, my BMS is well within the back bracket, and you can count the number of heatsink fin, mine is 6 and ur are 7 :) This BMS purchased fom Trianglab as a drop in replacement for Ender 3 v2 hotend (that what Phaetus advertise), turn out it's not since its too short for origin E3v2 hotend fan duct, back then I remember I had to print a new duct for it, my wild guess is they extend the length to become a real drop in replacement hence yours is longer.
![IMG_0450](https://user-images.githubusercontent.com/83712689/147703648-40be7096-36d8-46c7-8622-fb99e6412b65.jpg)

**Comment by plumpcheek** [comment]
And may I ask what version of your back bracket, look like the corner radius is corrected with your hotend, if you used beta0 version, so there two types of BMS hotend: one is short and narrow corner and one is long and wider corner :)

**Comment by DorjeDorf** [comment]
I used the Beta0 for CW2 one.

**Comment by mathisschmieder** [comment]
I can confirm the 51mm length of a recently bought Dragonfly BMS. Well, more like 50.93mm

**Comment by DorjeDorf** [comment]
Here are my measurements just to keep it in one place.
![IMG_1116](https://user-images.githubusercontent.com/45540765/147839210-0cd60795-de60-42d2-994e-ffd49ab41cc8.jpeg)
![IMG_1115](https://user-images.githubusercontent.com/45540765/147839211-525bc97a-6be5-4e5c-8da2-99ea2b263c5f.jpeg)

**Comment by DorjeDorf** [comment]
I just printed out the Beta1 toohead. 

Things I noticed for the BMS. 

1. The name of the toolhead on the Front part - now reads BMO and not BMS. 
2. In my case, the change to the corners for mounting don't change anything, but are a nice touch :)
3. **No changes** in terms of the cooling ducts. Their bottom tip starts at the end of the heatblock when it's without a sock. When I put a sock on - it's clearly vislble that the air will blow on the heatblock and not on the nozzle. I did a water bowl test - there was no center point for air converging beneath the nozzle. It got a bit better when I took the sock off, but still, nothing like what I can get with the Dragon SB toolhead. 

EDIT: Corrected to say there was **no** center point.

**Comment by AaronHerrick** [comment]
there are 2 different phaetus BMS toolheads. the older one, with 6 fins, is the one we did the mount for. the newer one, that they changed without telling anyone, has 7 fins and its slightly longer.  I'm hoping its about the same size as the Zodiac BMS, plus or minus .25mm that should be close enough

**Comment by mathisschmieder** [comment]
According to these https://cdn-3d.niceshops.com/upload/file/Technical_data_sheet_for_BMS_Hotend[0].pdf specs, the Zodiac BMS is 45.36mm from top of heat sink to bottom of heater block. This is absolutely in line with my recently bought 7-finned Phaetus Dragonfly BMS and with what DorjeDorf posted.

**Comment by mathisschmieder** [comment]
As far as I can tell, the beta2 parts fix this issue, at least with the 7 fin version. Top of toolhead to nozzle tip is bang on 61.5mm

**Comment by raymondh2** [comment]
@DorjeDorf Does beta2 fix these issues for you?

**Comment by DorjeDorf** [comment]
Bah I missed the callout. I will print it tomorrow and let you know.

**Comment by DorjeDorf** [comment]
Can confirm. Looks good. Haven't printed yet, but water bowl test went through great. Thank you.
