### ISSUE TITLE
[SB-beta] Phaetus BMS fit issue with toolhead rear

### ISSUE THREAD

**Issue by plumpcheek** [VoronDesign/Voron-Afterburner#31]
File print: stealthburner_toolhead_(phaetus_bms)-rear-cw1-beta0 (and front), the upper corner radius seem wider than the hot-end corner radius lead to the upper end of hot-end not sit flush and the bolt misalignment with hole below (a little, I can force it in). See picture below:
![IMG_0431](https://user-images.githubusercontent.com/83712689/147595505-d82f7f65-e5fa-4d71-82c3-4b2568facf02.jpg)

**Comment by wile-e1** [comment]
The CAD provided by Phaetus does not match actual parts.

![image](https://user-images.githubusercontent.com/34219833/147638442-393b636d-3109-4f69-b195-07884e2720f9.png)

The radius of the model shows 3mm, but measurements from actual heatsink are around 2mm.  The toolhead will be adjusted to suit.

**Comment by plumpcheek** [comment]
Thanks, closing this and wait for new toolhead.

**Comment by wile-e1** [comment]
Should be posted tomorrow.
