### ISSUE TITLE
San Ace B52 does not fit

### ISSUE THREAD

**Issue by Scroeder** [VoronDesign/Voron-Afterburner#34]
I have a problem mounting the B52 fan. Had to dremel out the screw hole, but it seems that 2mm in diameter are missing. 

[
![IMG_3683](https://user-images.githubusercontent.com/61126530/147603087-2d675a3c-cdb0-4c48-be99-a7e076769444.jpg)
![IMG_3684](https://user-images.githubusercontent.com/61126530/147603108-0e4252b0-c69a-4e98-a4c9-d3a83e7b4350.jpg)
](url)

**Comment by wile-e1** [comment]
I have added a little clearance to the fan cutout for SB Main Body based on BadNoob's feedback on his San Ace fan  I do not have a B52 to test fitment though.  If you could print Beta2 and report back, that would be fantastic.  Thanks!

**Comment by Scroeder** [comment]
Sure, where do I find the beta2 ?

**Comment by wile-e1** [comment]
My PR isn't merged yet, but you can access it from here:

[https://github.com/VoronDesign/Voron-Afterburner/pull/38](url)

**Comment by Scroeder** [comment]
Unfortunately it does not fit but definitely better. I removed a little material from the marked area. Now it fits so nice and flush. 
![image](https://user-images.githubusercontent.com/61126530/147706098-12c94d48-4740-48e9-b80e-4d4d0871baa5.jpeg)

![image](https://user-images.githubusercontent.com/61126530/147706123-3101ea30-b708-400f-8224-32dd2b510384.jpeg)

![image](https://user-images.githubusercontent.com/61126530/147706160-60fb6230-b366-427b-9829-f5fc5cc701a1.jpeg)

**Comment by raymondh2** [comment]
We have decided not to support this fan due to the B52 being a 52mm fan not fitting into the space constraints in the design. While it can be forced into place, we neither recommend nor condone this method of fitment.
