### ISSUE TITLE
How works the thermal leds gcode?

### ISSUE THREAD

**Issue by EraserFX** [VoronDesign/Voron-Afterburner#36]
stealthburner_leds.cfg

```
variable_thermal_config: {
        'extruder': {
            'cool_temp': 40,
            'leds': 'logo',
        },
        'heater_bed': {
            'cool_temp': 40,
            'leds': 'nozzle',
        },
    }
```
How do I use this code?

**Comment by wile-e1** [comment]
I believe this was an left-over snippet of code in the config.  I don't think it does anything just yet, but some people are working on some cool things and they will be posted when/if they get finished :)

please mark this issue closed unless you have further questions.

**Comment by EraserFX** [comment]
Oh NICE!! 
Thanks for this great Work on SB/CW2
