### ISSUE TITLE
SB main body face chamfer to compensate for elephants foot

### ISSUE THREAD

**Issue by elcrni** [VoronDesign/Voron-Afterburner#43]
As the title says, SB main body face could use a small chamfer to compensate for elephants for, it would also look nicer.

**Comment by AaronHerrick** [comment]
the SB main body is adhesion limited.  Adding a chamfer to top will cause issues with it popping off the bed and warping. you can easily trim off any elephant's foot with a blade.

**Comment by elcrni** [comment]
yes but i fo not have any issues with adhesion and lifting, so will just wait for CAD to be released and do it myself, not a big problem. many thanks
