### ISSUE TITLE
SB motor plate hole missing rectangular print hack thingy

### ISSUE THREAD

**Issue by austinvojta** [VoronDesign/Voron-Afterburner#44]
One hole still needs the (credit Timmit for the naming of this "feature"):
> Hole Bridging Assist Feature
> aka squircle hole
> aka HOSE: Hole Open Squaring Extra
> aka OAF: Overhang Assistance Feature
> aka OOF: Overhang Optimization Feature

https://github.com/VoronDesign/Voron-Afterburner/blob/sb-beta/STLs/Clockwork2/motor_plate-beta2.stl

![image](https://user-images.githubusercontent.com/36388567/147780120-f44fb313-ff44-479f-9760-8843f2af810f.png)

**Comment by timmit99** [comment]
@austinvojta Nailed it!

**Comment by wile-e1** [comment]
Noted and will be corrected for next revision.

**Comment by austinvojta** [comment]
Looks like this can be closed now, thanks Chris
