### ISSUE TITLE
Stealthburner + LGX top mounting screws to long

### ISSUE THREAD

**Issue by Clon1998** [VoronDesign/Voron-Afterburner#47]
I've noticed that the suggested M3x25 screws for the top holes of the sb are to long and therefore will thread through the plastic (if you force them, otherwise the top isn't secured properly) of the lgx-adapter. Using m3x20 solved that. I guess its worth pointing that out in the manual or to add a new adapter for the lgx.

**Comment by raymondh2** [comment]
As this is parts for a mod this doesn't belong here
