### ISSUE TITLE
Probe mount screws extend into back of Rapido 

### ISSUE THREAD

**Issue by xLAwildx** [VoronDesign/Voron-Afterburner#50]
The screwheads on the PINDA probe mount extend into the back of the Rapido tool head mount back.

**Comment by xLAwildx** [comment]
![20220101_140810](https://user-images.githubusercontent.com/90163082/147859321-cfe965c2-1b9f-40fc-a656-b0b2b947b036.jpg)

**Comment by wile-e1** [comment]
I'll look into this to see what I can do.

**Comment by xLAwildx** [comment]
It's the part known as pinion.stl in the switchwire release. It perfectly
fits the PINDA2 probe, so i thought it was officially supported.

**Comment by wile-e1** [comment]
> 
 You're absolutely right, this is supported.  I'm not familiar with Switchwire at all, so I didn't realize that's where this was from which is why I revised my initial comment.  Sorry for the confusion.

**Comment by wile-e1** [comment]
[Pinion-Revised v1.zip](https://github.com/VoronDesign/Voron-Afterburner/files/7800769/Pinion-Revised.v1.zip)
Can you please try and print this part and let me know if it works for you.

Also, I would highly recommend BHCS for these locations.  They take up much less height.

**Comment by raymondh2** [comment]
@xLAwildx Do the files Wile.e provided fix the issue for you?

**Comment by xLAwildx** [comment]
Printing the probe mount just now, but the stl looks good.

**Comment by xLAwildx** [comment]
![1641670124888375839815744483057](https://user-images.githubusercontent.com/90163082/148657156-44b01be4-2038-496b-bd05-c0f7966c28e0.jpg)
Screws on the probe mount are now verified to sit below the front edge of the x carriage. Problem solved.
