### ISSUE TITLE
Probe intersects with switchwire x carriage

### ISSUE THREAD

**Issue by xLAwildx** [VoronDesign/Voron-Afterburner#51]
PINDA style probe intersects with switchwire x carriage. There is a contour on the linear rail mount, but the opposite contour is missing from the x carraige.
![20220101_140858](https://user-images.githubusercontent.com/90163082/147859365-e3db36e4-0b56-481f-8971-b03d894842a2.jpg)
![20220101_140941](https://user-images.githubusercontent.com/90163082/147859367-8b51bca8-8217-41ac-90bc-8be207a0fb99.jpg)

**Comment by stvptrsn** [comment]
Hi xLAwildx, the pinda probe has a really short, like 2.2mm, sense distance.  At the point the probe is interfering with the x carriage, like in your pictures, it is too far off the bed to trigger.  I just confirmed this on my Switchwire with the pinda probe installed
![IMG_4482](https://user-images.githubusercontent.com/46913624/148151888-7150afea-f2f3-4ac1-901c-c6fb55f58941.jpeg)
.

**Comment by nife87** [comment]
I agree that its sense distance is short (I have a genuine SuperPINDA), but having just converted from AB v2.4r1 to SB beta 3 I disagree that the clearance is large enough. My probe is sitting 1.4mm above the nozzle, and there was not enough space, so I had to grind the corners a bit. See #57.

**Comment by xLAwildx** [comment]
![20220108_131812](https://user-images.githubusercontent.com/90163082/148656947-ed3f1a77-7ca7-4081-9326-3c0042e03d63.jpg)
You can see here where I manually carved out part of each side of the x carriage so that I could move the probe high enough.
![16416698880304459808271133929078](https://user-images.githubusercontent.com/90163082/148657059-ca94563f-6ca3-4d5e-8021-d9034118c325.jpg)
You can see in the second pic that this way I can move the probe mount up to level with the bottom of the carriage, which should be the max height. (this is the AB carriage)

**Comment by wile-e1** [comment]
This issue should now be resolved with PR https://github.com/VoronDesign/Voron-Afterburner/pull/67
