### ISSUE TITLE
Bottom heat sink fin on V6 is not properly cooled.  

### ISSUE THREAD

**Issue by Dfdye** [VoronDesign/Voron-Afterburner#52]
The bottom heat sink fin on the E3D V6 heat sink is not enclosed within the area cooled by the tool-head fan.  The V6 heat sink measures 42.7 mm from end to end, and 39mm from the upper inside edge of the mounting groove to the bottom of the lowest cooling fin.  The SB mount for the V6 measures approximately 36 mm from the upper edge of the mounting groove to the bottom ridge of the cooling duct that encloses the heat sink (about 3mm short of what is needed, if my measurements are correct).  This leaves the lowest fin of the heat sink un-cooled, and in my case seems to have caused heat creep issues for me while printing PETG,  I don't have definitive evidence for this, but anecdotally the PETG will not experience heat creep when fitted with the ABBN.  As a point of comparison, the ABBN V6 mount appears to fully enclose the V6 heat sink within the area cooled by the tool head fan.

**Comment by AaronHerrick** [comment]
this is certainly possible, what heat break are you using?  if it is one with a teflon liner, have you recently changed it the teflon liners oxidize over time, even at low temperatures.

**Comment by Dfdye** [comment]
I tested with both a Ti heat break and a bi-metal Ti/Cu heat break.  Both were "all metal" and did not have tubing in the heating zone.  It may well be that I have something else going on (which is why I added the caveat in the initial post!), but so far it seems to be that the cooling from the SB is not working exactly right for my rig.

**Comment by raymondh2** [comment]
We are looking into this

**Comment by Dfdye** [comment]
Great!  Thanks for all of the work that you have already put into this.  You and the rest of the crew working on this are fantastic!

**Comment by wile-e1** [comment]
A revised toolhead has been created and will come out with the next round of updates. Expect to see in soon.

**Comment by Dfdye** [comment]
You guys are unbelievable!  Thanks so much for looking into it.

**Comment by govido** [comment]
![IMG_20220115_133052](https://user-images.githubusercontent.com/12106056/149622227-8eab52b8-8f77-4c7d-bb2f-171b18bfaeea.jpg)
![IMG_20220115_133802](https://user-images.githubusercontent.com/12106056/149622230-bfa89c2c-b40e-4751-9af5-8eef15461273.jpg)

I can confirm that it is fixed with beta2 :)
