### ISSUE TITLE
E3D Volcano Edition - Stealthburner

### ISSUE THREAD

**Issue by Red-112** [VoronDesign/Voron-Afterburner#54]
The current E3D V6 hot end block is 11.5mm thick. The E3D volcano hot end block is 20mm thick. Would it be possible to extend the current V6 version to quickly create the Stealthburner volcano version? Thank you in advance
[V6-Volcano-Block-(PT100)_PUBLI.pdf](https://github.com/VoronDesign/Voron-Afterburner/files/7823012/V6-Volcano-Block-.PT100._PUBLI.pdf)
[V6-BLOCK-CARTRIDGE.pdf](https://github.com/VoronDesign/Voron-Afterburner/files/7823013/V6-BLOCK-CARTRIDGE.pdf)
!

**Comment by wile-e1** [comment]
Unfortunately, there will no official Volcano support.  The hotend is just too long and causes compromises to the design to support all the work and testing that goes into  making sure the design is "up to par".  The Volcano hotend was not even officially supported on Afterburner.

The community is free to create a User Mod though.
