### ISSUE TITLE
Mention bmg gear grub screw in CW2 assembly Manual

### ISSUE THREAD

**Issue by digital-scrappy** [VoronDesign/Voron-Afterburner#58]
Hi, I just recently built my first Voron ( a Trident) and switched the two bmg gears since the grub screws were not mentioned in the manual. 
For a first time builder it might not be clear that the drive gear needs to be the one with the grub screw. I suggest to add a comment in the Stealthburner Manual in regards to this.

( I was  assembling afterburner but I guess making the change in the CW2 manual should have higher priority)-

**Comment by stvptrsn** [comment]
Thanks for the suggestion, in the next manual revision we were intending to call out the locations where locktite is recommended and that will take care of this.
