### ISSUE TITLE
Two sharp corners broke layers while fast printing 

### ISSUE THREAD

**Issue by adama119** [VoronDesign/Voron-Afterburner#59]
![IMG_3095](https://user-images.githubusercontent.com/3455270/148685554-40430f4c-ebbd-40fb-a8ba-a00deaafcf56.jpg)

Since CW2 is beta version, I've just tried to use  Stealthburner on my My Voron2.4  with Clockwork 1 and Phaetus  dragon hotend. (Voron-Dragon HF Hotend)
But the LED sharp corner touch layer while printing randomly.   Sometimes layers are broken by the corner.
Can you fix this?  Thanks for all the work!

stealthburner_main_body_beta2.stl
stealthburner_toolhead_(dragon)-front-beta0.stl
stealthburner_toolhead_(dragon)-rear-cw1-beta0.stl

**Comment by raymondh2** [comment]
The way you make it sound seems like your prints are warping into the ducts? Can you please elaborate on this issue.

**Comment by AaronHerrick** [comment]
At all times, that corner is 2.3 mm higher than the nozzle unless there is something broken on your printer.

**Comment by stantang986** [comment]
It happened to me as well when using Voron-Dragon HF Hotend only. 
This hotend seems a lit bit shorter than normal one.

**Comment by adama119** [comment]
> It happened to me as well when using Voron-Dragon HF Hotend only.
> This hotend seems a lit bit shorter than normal one.

Exactly the same,  My hotend is  Voron-Dragon HF Hotend

**Comment by stantang986** [comment]
If you don't want to change stl file, 
you can try to screw the toolhead front part first and then cover the main body part(the out red one), it may save you just a little bit distance. 
Or, don't mind looking thing, jst cut it...

**Comment by wile-e1** [comment]
I took a closer inspection to this issue and it does have some merit.  I have been using the Dragon mount and definitely noticed my toolhead is close to the build plate, but it still shouldn't be wiping your prints out unless they're warping or peeling up from the print surface.

With that said, the cutout that I was provided looks like it places the nozzle about 1.4mm higher than the target height, which absolutely does eat into the clearance. The Dragon mount has been adjust and will be updated on the repo soon. Please keep an eye out for Beta1 version of the toolhead files.

Thank you for bringing the issue to our attention.

**Comment by vjeko2404** [comment]
I can confirm that with the dragon hotend and SB, the nozzle tip was only 0.7mm higher from the SB casing. My solution was to print 1mm distance washer for inbetween HE mount and the body.
