### ISSUE TITLE
LED (RGB) Flashing

### ISSUE THREAD

**Issue by acosano** [VoronDesign/Voron-Afterburner#62]
My apologies if I posting int the wrong place but I have try FB and Discord with no success on anyone given response. I printed 2 sets of the Stealthburner. One is on my SW with a SKR1.4 and the other one I use on my new v2 build with Octopus Pro. The LED (RGB) working fine on the SW but not on the V2. the lights keep flashing with different colors and I can't control it. I'm using a harness from KB3D that came with the 3 additional wires for it. I'm using PIN0 <- Cero. I can measure the current off 4.99v. Any help would help

**Comment by wile-e1** [comment]
> My apologies if I posting int the wrong place but I have try FB and Discord with no success on anyone given response. I printed 2 sets of the Stealthburner. One is on my SW with a SKR1.4 and the other one I use on my new v2 build with Octopus Pro. The LED (RGB) working fine on the SW but not on the V2. the lights keep flashing with different colors and I can't control it. I'm using a harness from KB3D that came with the 3 additional wires for it. I'm using PIN0 <- Cero. I can measure the current off 4.99v. Any help would help

Hi there, unfortunately this isn't really the right place to get help with this.  Issues are to keep document and keep track of design and operation issues with Stealthburner or Clockwork2.  The issue with your LEDs is an issue with your control board or possibly something to do with your wiring.  Some LEDs seem to be a little fussy about working on certain control boards.

The LED Discussion or the Electronics section of the Voron Discord are your best bet for getting help resolving this issue.
