### ISSUE TITLE
[FR] - manual - TOC should have hyperlinks to content

### ISSUE THREAD

**Issue by bassco** [VoronDesign/Voron-Afterburner#65]
When clicking the page number or section in the table of Contents I would expect Acrobat Reader to jump to that page in the manual. This feature was introduced in the Trident manual and is a QOL improvement.

**Comment by wile-e1** [comment]
I agree that the hyperlinks would be helpful, but this is a Beta project that is subject to change and the manual is only 28 pages long.  Contrast that to the Trident manual that is 279 pages long.

We would absolutely love to incorporate hyperlinks in full-release version manuals though, as they make it very quick and easy to access the specific information.
