### ISSUE TITLE
Keep Afterburner Repo Updated

### ISSUE THREAD

**Issue by ctilley83** [VoronDesign/Voron-Afterburner#7]
The files in this repo are not updated compared to the stls in the Voron-2 repo. Keep this repo updated at all times.

**Comment by excessnet** [comment]
IMO, should be removed from V2 repo and use only the Afterburner repo (adding a MD file to link it there).

**Comment by dingyifei** [comment]
^Agreed, one way to do it is to remove all the afterburner files in the v2 repo and add this repo to the v2 as a submodule.
