### ISSUE TITLE
No room for the collet on a Pheatus BMS

### ISSUE THREAD

**Issue by WanderW** [VoronDesign/Voron-Afterburner#78]
Hi, I'm trying to build a SB with a Pheatus BMS (6 fin version) I previously used this hotend in an ABBN-30 and it worked great there. In the SB it doesn't fit, because there is no room for the collet that holds the PTFE tube. 
Because there is no room for the collar, the screwholes don't line up with the heatset inserts.

Stealthburner:
![20220131_133805](https://user-images.githubusercontent.com/12582377/151829451-9c39218e-a9a1-456b-85a5-809b6d7baafb.jpg)

For reference the same mount from ABBN-30:
![20220131_133751](https://user-images.githubusercontent.com/12582377/151829477-787be8b8-4ff0-4fb8-b254-c34c68d4625a.jpg)

**Comment by DorjeDorf** [comment]
Remove the collet - that's what I did. It won't be necessary considering the pressure coming from both halves of the mount that hold the tube in place.

**Comment by WanderW** [comment]
The collet is fixed permanently to the BMS. As far as I can see you can only remove it by destroying it.
I'd like to keep my BMS intact so I can use (or sell) it in the future.

**Comment by timmit99** [comment]
Keeping the collet installed, while keeping the hotend stock, can make removal of the PTFE impossible without a full disassembly. Also, you would want to fit a collet clip in there as well\ to keep the tube from moving up and down during retract moves.

Removing the collet entirely and just having a spare one incase it gets damaged and you want to reinstall later is probably the easiest solution unless you see a NEED to have the PTFE captured inside the toolhead.

**Comment by raymondh2** [comment]
Closing as we will not be making space for the collet.

**Comment by raymondh2** [comment]
After discussion, removing the collet, while potentially damaging to the collet, allows for much easier replacement of the PTFE and servicing of the hotend. In this case we decided against adding the cutout therefore requiring the collet be removed.
