### ISSUE TITLE
Incorrect screws in manual for front plate

### ISSUE THREAD

**Issue by jdknoll** [VoronDesign/Voron-Afterburner#84]
The last page of the manual specifies two m3 x 25 screws for the front plate on clockwork 2, but it should be m3 x 20mm or else the screws stick through pretty far.

**Comment by wile-e1** [comment]
> The last page of the manual specifies two m3 x 25 screws for the front plate on clockwork 2, but it should be m3 x 20mm or else the screws stick through pretty far.

The page where the bolts are showed also has a big note next to it explaining this.

The longer bolts on CW2 are intended to allow the bolts to remain installed to support the front face of SB and also allow you to drop the toolhead out the bottom without having to remove the front cover.

![image](https://user-images.githubusercontent.com/34219833/153051336-2903c438-5d45-4b81-a49f-d4f482dfcfe2.png)

**Comment by timmit99** [comment]
@jdknoll  the screws are designed to be a bit long to allow for them to be loosened for toolhead removal without coming out of the heat-sets entirely.
=)

**Comment by jdknoll** [comment]
Thank you for the response! With the highlighted note, my assumption was that you would loosen them slightly as in just enough to loosen them, but not remove them - not that you would leave them in the insert as you swap out, so when I saw the screw go past to where the guidler is, I assumed that something was wrong in my assembly. That said, thank you again for the clarification.
