### ISSUE TITLE
Phaetus BMS7 rear cw2 - slicing error

### ISSUE THREAD

**Issue by cdesgagne1212** [VoronDesign/Voron-Afterburner#87]
There is an issue with the BMS 7 fin rear new release.  (stealthburner_toolhead_(phaetus_bms7)-rear-cw2-beta3.stl)
There is a hole on the side of the wall that is supposed to hide the m3 x 50mm bolt. This hole only appears when the piece is sliced (at any layer height). I don't think that this is a major issue but it would be good to give a look at it 

![image](https://user-images.githubusercontent.com/99681698/153921166-5b962fc2-212c-4174-a1a6-0f224309a647.png)

In comparison, the Dragon rear one is correct (stealthburner_toolhead_(dragon)-rear-cw2-beta2.stl)

![image](https://user-images.githubusercontent.com/99681698/153921235-106252e8-e99a-45a7-bb16-664da380e7da.png)

Edit: the hole appears also on the 6 fin version. 

#86

**Comment by wile-e1** [comment]
Thank you for notifying us.  I will update the toolheads as soon as I get  a chance.
