### ISSUE TITLE
Rapido mount is oriented the wrong way

### ISSUE THREAD

**Issue by riley-williams** [VoronDesign/Voron-Afterburner#90]
The current rapido mounting orientation blocks the outlet on one side of the back piece (screwed in):

![IMG_6666](https://user-images.githubusercontent.com/1980773/154341177-74416155-4881-4a89-a5f8-17661c379c32.jpeg)

It looks like the opposite rotation was intended as that would hold it up against the front and out of the way of the back outlet. Unless rapidos come in both orientations...

![IMG_6668](https://user-images.githubusercontent.com/1980773/154341417-40201599-1019-4163-a420-1e4d098d7a41.jpeg)

**Comment by DaLeberkasPepi** [comment]
If you carefully remove the 3 stabilizing screws, you can rotate the heat block. But be careful when tightening the 3 screws again to go carefully and bolt them evenly, so you don't bend the heatbreak.

**Comment by riley-williams** [comment]
Is this something every rapido owner will be expected to do? If all rapidos come in 1 or 2 orientations, it seems like it would be much easier to just provide the parts that support the factory orientations.

**Comment by riley-williams** [comment]
After playing with it for a little bit, I've changed my mind. Seems like a reasonably easy thing to ask everyone to do. I'll track down a set of official instructions from phaetus on safe reassembly and create a PR for a README that might help with future confusion for people that get their rapido in the 2 unsupported factory orientations

**Comment by wile-e1** [comment]
Is your Rapido a Phaetus or from some other vendor?

My hotend is direct from Phaetus:
![image](https://user-images.githubusercontent.com/34219833/154567037-c320aca7-de8f-4e77-b6d3-97d670f46b1c.png)


I have read reports of people with TL Rapidos that come oriented differently.

If it's a random assembly, then there's not much that can be done other than to document how to adjust for it.

**Comment by riley-williams** [comment]
Mine is a TL Rapido

**Comment by nathanielhudson** [comment]
If you want another datapoint, I also have a TL Rapido and had the same factory orientation as riley. Disassembling and reassembling to correct this wasn’t too bad though.

**Comment by wile-e1** [comment]
Since we've added the note for now, thanks to @riley-williams , I'm going to consider this issue closed for the time being.
