### ISSUE TITLE
-'s instead of +'s on change log

### ISSUE THREAD

**Issue by austinvojta** [VoronDesign/Voron-Afterburner#96]
Super minor -- but the incoming files are marked with - instead of + on the latest change log entry. https://github.com/VoronDesign/Voron-Afterburner/tree/sb-beta#2022-02-18---clockwork-2-body-and-latch-updates-93

**Comment by wile-e1** [comment]
There is already a PR for this correction.  Thank you for taking the time to notify us though.

**Comment by raymondh2** [comment]
Fixed in #97
