### ISSUE TITLE
main_body-beta7 possible weak point

### ISSUE THREAD

**Issue by wattsie** [VoronDesign/Voron-Afterburner#99]
Hi All,
  Just started printing and playing with Clockwork2.

  I mock fitted the leavers to the "main_body-beta7", and while it might have been my heavy hand, the top guide section snapped while testing the leaver action. (currently printing another while trying to clean up my print quality)

  Note: I didn't have the motor plate attached, so understand it wasn't fully supported on both sides.

  However, wondering, as there is some additional space between this guide and the leaver, would it be worth adding some more support to the top of this guide to add strength?

![main_body-beta7_issue](https://user-images.githubusercontent.com/5244866/155044304-d83aa186-743d-4cd6-8816-6a9d18a6d163.png)

Possible additional support location?
![IMG_1639](https://user-images.githubusercontent.com/5244866/155046163-d37585cf-5594-473e-b444-d16a0b313f4e.png)

  Many thanks,

Cheers.

**Comment by wile-e1** [comment]
This issue has already been sorted out prior to this post.  The parts are being test-printed but have not yet been posted.  Please stay tuned for the next update.

**Comment by wattsie** [comment]
Thanks @wile-e1 ill wait to test next version.

**Comment by wile-e1** [comment]
> Thanks @wile-e1 ill wait to test next version.

Posted in SB Feedback channel.

This space didn't open up until the last revision of the latch and I wanted to test that first before changing anything else.

![Inventor_tWl6ZOuGVg1](https://user-images.githubusercontent.com/34219833/155065426-7c4d1189-5e12-4717-9792-223465ad85bc.png)
